### ISSUE TITLE
trouble on incapsulate

### ISSUE THREAD

**Issue by cybermerlin** [jasmine/jasmine.github.io#88] opened 2017-12-28 10:04 UTC
```
....FA Jasmine spec timed out. Resetting the WebDriver Control
Flow.
F

Failures:
1) invoice incoming Adding Invoice row
  Message:
    Error: Timeout - Async callback was not invoked within time
out specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within time
out specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:475:11)
        at tryOnTimeout (timers.js:310:5)
        at Timer.listOnTimeout (timers.js:270:5)
  Message:
    Failed: Element "INVOICE_INCOMING.btnAdd" taking too long i
n the DOM.
    Wait timed out after 60009ms
  Stack:
    TimeoutError: Element "INVOICE_INCOMING.btnAdd" taking too
long in the DOM.
    Wait timed out after 60009ms
        at R:\lw\node_modules\selenium-webdriver\lib\promise.js
:2201:17
        at ManagedPromise.invokeCallback_ (R:\lw\node_modules\s
elenium-webdriver\lib\promise.js:1376:14)
        at TaskQueue.execute_ (R:\lw\node_modules\selenium-webd
river\lib\promise.js:3084:14)
        at TaskQueue.executeNext_ (R:\lw\node_modules\selenium-
webdriver\lib\promise.js:3067:27)
        at asyncRun (R:\lw\node_modules\selenium-webdriver\lib\
promise.js:2927:27)
        at R:\lw\node_modules\selenium-webdriver\lib\promise.js
:668:7
        at <anonymous>
        at process._tickDomainCallback (internal/process/next_t
ick.js:228:7)
    From: Task: Element "INVOICE_INCOMING.btnAdd" taking too lo
ng in the DOM.
        at scheduleWait (R:\lw\node_modules\selenium-webdriver\
lib\promise.js:2188:20)
        at ControlFlow.wait (R:\lw\node_modules\selenium-webdri
ver\lib\promise.js:2517:12)
        at Driver.wait (R:\lw\node_modules\selenium-webdriver\l
ib\webdriver.js:934:29)
        at run (R:\lw\node_modules\protractor\built\browser.js:
59:33)
        at ProtractorBrowser.to.(anonymous function) [as wait]
(R:\lw\node_modules\protractor\built\browser.js:67:16)
        at Grid.btnAdd (R:/lw/tests/e2e/Grid.js:50:21)
        at UserContext.<anonymous> (R:/lw/tests/e2e/invoice/tes
t.js:30:18)
        at R:\lw\node_modules\jasminewd2\index.js:112:25
        at new ManagedPromise (R:\lw\node_modules\selenium-webd
river\lib\promise.js:1077:7)
        at ControlFlow.promise (R:\lw\node_modules\selenium-web
driver\lib\promise.js:2505:12)
    From: Task: Run it("Adding Invoice row") in control flow
        at UserContext.<anonymous> (R:\lw\node_modules\jasminew
d2\index.js:94:19)
    From asynchronous test:
    Error
        at Suite.describe (R:/lw/tests/e2e/invoice/test.js:29:9
)
        at Suite.describe (R:/lw/tests/e2e/invoice/test.js:11:5
)
        at Object.<anonymous> (R:/lw/tests/e2e/invoice/test.js:
10:1)
```

**Comment by cybermerlin** [comment] 2017-12-28 10:04
```
const EC = protractor.ExpectedConditions;

/**
 * @cfg {Boolean} [autorun]
 *
 * @class Core.tests.e2e.Grid
 */
class Grid {
    appName = '';
    tableName = '';
    forms = [];

    constructor(cfg) {
        cfg = cfg || {};
        if ( cfg.autorun ) {
            this.run();
        }
        this.el();
    }


    //region elements
    el() {
        if ( !this._el ) {
            browser.wait(
                async () => {
                    await browser.executeScript(`let o = window.system.apps.runned
                          .find(app => app.params.tableName === "${this.tableName}");
                        if (o && !o.$box.hasClass("test_${this.appName}"))
                          return o.$box.addClass("test_${this.appName}");`);
                    return EC.presenceOf(element(by.css(`.test_${this.appName}`)));
                },
                browser.params.timeWaitSelEl,
                `Element "${this.tableName}" too long in the DOM.`);
            this._el = element(by.css(`.test_${this.appName}`));
            this._appForm = element(by.css(`.${this.appName}`));
        }

        return this._el || null;
    }

    appForm() {
        return this._appForm;
    }

    btnAdd() {
        let self = this;

        if ( !self._btnAdd )
            browser.wait(EC.presenceOf(this._btnAdd = this.el().element(by.css('.Grid-Toolbar--IconView-add'))),
                browser.params.timeWaitSelEl,
                `Element "${this.tableName}.btnAdd" taking too long in the DOM.`);

        return this._btnAdd;
    }

    //endregion


    run() {
        browser.executeScript(`return window.system.apps.run("${this.appName}");`);
    }
}

export default Grid;
```

**Comment by cybermerlin** [comment] 2017-12-28 10:05
```js
import Form from './Form';
import e2e from '../..';

const EC = protractor.ExpectedConditions;

/**
 * @cfg {Boolean} [autorun]
 *
 * @class Core.tests.e2e.invoice.incoming.Grid
 */
class Grid extends e2e.Grid {
    appName = 'invoice_incoming';
    tableName = 'INVOICE_INCOMING';


    //region elements
    //endregion

    /**
     * add service
     * @param {Core.tests.e2e.invoice.incoming.Service} [f]
     */
    addService(f) {
        f = f || this.forms[0];
        f.btnAdd().click();
    }
}

export default Grid;
```

**Comment by cybermerlin** [comment] 2017-12-28 10:06
if I write class Grid without extends, then will be all right

**Comment by sgravrock** [comment] 2017-12-28 17:38
I can't tell what's going on here. You've posted a bunch of code but haven't included either the test that's failing or the definition of the `e2e.Grid` class that seems to be part of the problem. The error message suggests that your test is not telling Jasmine that it's done (either by calling the `done` callback or by resolving a returned promise), but I have no way of knowing why that's happening.

Some things you can do:

* Check the browser console for errors and fix any that you find.
* Debug your failing test using all the techniques that you'd use to debug non-test async code that isn't working correctly.
* Remove code until you're left with the smallest possible self-contained example that demonstrates the problem. There's a good chance that you'll figure out the problem in the process. Even if you don't, you'll be in a much better position to ask others for help.
* Ask for help on a Protractor forum, since it looks like your setup is heavily Protractor-centric. If you can't reproduce the problem without Protractor, then that community is in a much better position to help you than we are.

I'm going to close this as it isn't a Jasmine documentation issue. Feel free to open an issue on [the main Jasmine repo](https://github.com/jasmine/jasmine/issues) if you think you might have found a bug in Jasmine, or send questions about writing or debugging tests to the [mailing list](jasmine-js@googlegroups.com). In either case, please provide a self-contained, minimal, run-able demo of the problem.

**Closed by sgravrock** 2017-12-28 17:39 UTC
