### ISSUE TITLE
event.stopImmediatePropagation() cannot be tested

### ISSUE THREAD

**Issue by dmitri777** [jasmine/jasmine.github.io#77] opened 2017-09-11 15:43 UTC
For some reason, dispatchEvent() and event.stopImmediatePropagation() are not working together well, see example below. All 3 listeners do fire, even if the first one asks for immediate stop of propagation

	let count = 0;
	fit('should test listeners', () => {
		document.body.addEventListener('click', (event: MouseEvent) => {
			event.stopImmediatePropagation();
			console.log('listener 1 running');
			count++;
			event.stopImmediatePropagation();
		});

		document.body.addEventListener('click', (event: MouseEvent) => {
			console.log('listener 2 running');
			count++;
		});

		document.body.addEventListener('click', (event: MouseEvent) => {
			console.log('listener 3 running');
			count++;
		});

		document.body.dispatchEvent(new MouseEvent('click', { bubbles: true }));

		expect(count).toEqual(1); // fails - is actually 3, even with event.stopImmediatePropagation() in the 1st listener

	});

**Comment by sgravrock** [comment] 2017-09-11 17:14
I haven't been able to reproduce this. I did a minimal conversion to JS of the test code that you provided (removing type signatures and changing let to var) and it passed in all browsers that I have ready access to. I also suspect that the problem doesn't have to do with Jasmine, since Jasmine doesn't affect the way the browser handles DOM events in any way. Is there something else in your system (a library, perhaps?) that could be doing something to the browser's event handling?

I'm going to close this issue because it doesn't appear to be related to Jasmine and because this repo is for Jasmine's documentation, not Jasmine itself. But please feel free to open a new issue at https://github.com/jasmine/jasmine/issues if you still think this is an issue with Jasmine. It would help to know what browser you're using, what Jasmine version you're using, and whether there is any other code loaded besides Jasmine and the snippet above.

Thanks for using Jasmine!

**Closed by sgravrock** 2017-09-11 17:14 UTC
